### ISSUE TITLE
AppCDS

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/openjdk-ev3#16]
JDK 10 comes with AppCDS, which could make the JVM startup faster.

**Comment by jabrena** [comment]
What is your idea?

**Comment by JakubVanek** [comment]
My idea is to  include ev3dev-lang-java + logging libs in there.

**Comment by jabrena** [comment]
Give me some hours to explain in detail the possible alternatives.
It is quite interesting the proposal

**Comment by JakubVanek** [comment]
It is just a way of runtime caching, not a build-time cache. It should be manually generated on the first JVM start. http://openjdk.java.net/jeps/310

**Comment by JakubVanek** [comment]
This should be handled in the installer.
