### ISSUE TITLE
Jigsaw

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/openjdk-ev3#17]
After the java libraries are converted to jigsaw modules, they should be distributed with the EV3 runtime.

**Comment by jabrena** [comment]
If you like, we could continue this discussion in the library.

Related issue:
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/441

**Comment by JakubVanek** [comment]
Related to https://github.com/ev3dev-lang-java/installer/issues/1 , which could download the libraries and install them.
