### ISSUE TITLE
Use external softfloat library for higher softfp precision

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/openjdk-ev3#22]
http://mail.openjdk.java.net/pipermail/aarch32-port-dev/2016-December/000672.html

**Comment by jabrena** [comment]
What is the idea? Simple curiosity :)

**Comment by JakubVanek** [comment]
f287079823013d99712adb5b2873bd95ab8e91b3 + f814e5f7e4c4253fd825088085ecfaafdcb0a7d3 add support for this

**Comment by JakubVanek** [comment]
done, though we should test it
