### ISSUE TITLE
Build OpenJDK10 for Debian Jessie

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/openjdk-ev3#23]
Hi @JakubVanek,

Now we have the support for Debian Stretch and it is nice, but for old users, maybe if we could compile, the could experiment. Did you try?

``` Docker
FROM debian:8.9
```

Related issue:
https://github.com/ev3dev/ev3dev/issues/1056

**Comment by JakubVanek** [comment]
Hmmm, that should freeze the repositories in an old state. It might work. However I'm not sure how much we need to (and want to) support Jessie.

The old users now simply have to flash a new Stretch development snapshot. If they don't want to, Java 8 will still work for them (we would just need to integrate debian version branching to the installer).

It's a bit unfortunate that Jessie is still the "main" ev3dev release.

If you want to build it, try changing 'stretch' to 'jessie' in `system/apt.sources.list.debian` and replacing the `FROM` line in `system/Dockerfile`.

**Comment by JakubVanek** [comment]
Hi, I've tried it and it is still failing.
```
# apt-get install crossbuild-essential-armel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 crossbuild-essential-armel : Depends: gcc-arm-linux-gnueabi (>= 4.9.1-1) but it is not going to be installed
                              Depends: g++-arm-linux-gnueabi (>= 4.9.1-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

It might be possible to manually download all the packages to manually construct the required system.

**Comment by jabrena** [comment]
Hi mate,

OMG, it continues failing. Can you try manually please?

Cheers

**Comment by jabrena** [comment]
It is not necessary
