### ISSUE TITLE
Add support for Debian packages

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/openjdk-ev3#25]
We probably want to package this as a normal java package. That would make it automatically compatible with http://github.com/ev3dev-lang-java/openjdk-system

**Comment by JakubVanek** [comment]
Basic support should be complete, just maybe a different repo/jenkins job should be created.

**Comment by jabrena** [comment]
We will create it, but litle by litle :)

**Comment by JakubVanek** [comment]
I have made an interesting observation - for libopenmpt it was multiple times faster to run the build natively on Odroid-HC2 in a Debian stretch armel chroot than it was to run it in QEMU on my Core2Duo P8600.

**Comment by JakubVanek** [comment]
Though compiling libopenmpt is quite CPU-intensive because it has to be compiled with GCC. The effect on IO-intensive tasks may not be significant. However running tar with compression in qemu is also quite slow.

**Comment by JakubVanek** [comment]
Hmmmm, the current setup is probably enough. Packaging stuff probably can stay here. The package build is done on the developer computer only and splitting it to a separate repository would create unnecessary fragmentation.
