### ISSUE TITLE
Upstream our patches

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/openjdk-ev3#27]
Patch written:
- [x] Memory barrier patch - incorporated in JDK12
- [x] ARM build flags patches - [part 1](https://github.com/ev3dev-lang-java/openjdk-ev3/blob/master/upstream/arm1.patch) and [part 2](https://github.com/ev3dev-lang-java/openjdk-ev3/blob/master/upstream/arm2.patch)
- [x] AssumeMP patch - [draft](https://github.com/ev3dev-lang-java/openjdk-ev3/blob/master/upstream/assumemp.patch)
- [x] Remove softfloat workaround - [draft](https://github.com/ev3dev-lang-java/openjdk-ev3/blob/master/upstream/softfloat.patch)
- [x] Generalized Debian JNI library path patch - [draft](https://github.com/ev3dev-lang-java/openjdk-ev3/blob/master/upstream/jni.patch)

Patch tested:
- [x] Memory barrier patch - incorporated in JDK12
- [x] ARM build flags patches - done [on CI](https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk12_build_ev3_linux/21/) for ARMv5 and locally for ARMv7
- [x] AssumeMP patch - our JDK11 builds include it
- [x] Remove softfloat workaround - done but some discussion is needed
- [x] Generalized Debian JNI library path patch

Sent to JDK Master:
- [x] Memory barrier patch
- [x] ARM build flags patches
- [x] Remove softfloat workaround
- [x] Generalized Debian JNI library path patch - done locally

Incorporated in JDK Master:
- [x] Memory barrier patch - [JDK-8213826](https://bugs.openjdk.java.net/browse/JDK-8213826)
- [x] ARM build flags patches - [JDK-8214466](https://bugs.openjdk.java.net/browse/JDK-8214466), [JDK-8214465](https://bugs.openjdk.java.net/browse/JDK-8214465)
- [ ] Remove softfloat workaround - in progress, [JDK-8215902](https://bugs.openjdk.java.net/browse/JDK-8215902)
- [x] Generalized Debian JNI library path patch - [JDK-8214332](https://bugs.openjdk.java.net/browse/JDK-8214332)

Sent to JDK11:
- [ ] Memory barrier patch
- [ ] ARM build flags patches
- [ ] AssumeMP patch
- [ ] Remove softfloat workaround
- [ ] Generalized Debian JNI library path patch

Submit to JDK11:
- [ ] Memory barrier patch
- [ ] ARM build flags patches
- [ ] AssumeMP patch
- [ ] Remove softfloat workaround
- [ ] Generalized Debian JNI library path patch

**Comment by JakubVanek** [comment]
Memory barrier patch sent: https://pastebin.com/JPqHS55X

**Comment by JakubVanek** [comment]
Optimization patch sent: https://pastebin.com/k2dQQ86B

**Comment by JakubVanek** [comment]
AssumeMP for OpenJDK <12 waits here: [upstream/assumemp.patch](https://github.com/ev3dev-lang-java/openjdk-ev3/blob/master/upstream/assumemp.patch)
Softfloat workaround removal waits here: [upstream/softfloat.patch](https://github.com/ev3dev-lang-java/openjdk-ev3/blob/master/upstream/softfloat.patch)

**Comment by JakubVanek** [comment]
Maybe even the debian library patch could be reworked - a generic custom default path switch could be added.

**Comment by JakubVanek** [comment]
I think I can do it in three rounds:
1. Barriers + Optimizations
2. SoftFloat + AssumeMP
3. Debian JNI

**Comment by JakubVanek** [comment]
Optimization patch mail drafts:
1/2: https://pastebin.com/Mdn0Vf7c
2/2: https://pastebin.com/K8FeZTfK

**Comment by jabrena** [comment]
This issue is outdated
