### ISSUE TITLE
Reconsider the usage of Minimal VM

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/openjdk-ev3#28]
I think we could reconsider whether the Minimal JVM wouldn't be better than the Client JVM. According to sources on the internet, it has smaller memory footprint, but it also lacks manageability options (which are used in a dedicated gradle task).
http://openjdk.java.net/jeps/148

**Comment by jabrena** [comment]
We could evolve @JakubVanek.

Now, we have 2 options:

- A complete JDK
- A minimal JRI

We offer, the second option, but the user could start the first one. What options are used in a dedicated gradle task?

**Comment by JakubVanek** [comment]
The options are related to [JMX management](https://github.com/ev3dev-lang-java/ev3dev-lang-java/blob/b594c086a86d431112bce34b987f10b22e056127/gradle/deploy.gradle#L152). The selected JVM is orthogonal to the distribution - we can ship JDK with Minimal JVM as well.

Later, if we decide to go forward, we should compare memory usage and performance between Minimal and Client VMs.

**Comment by jabrena** [comment]
Do you have a build to test?
Can you create a new tar.gz maintaining previous JRI?

**Comment by jabrena** [comment]
```
runtime + full set of classes => JDK
some runtime + reduced set of classes => JRI
some runtime is HotSpot configured as either Client or Minimal
```

**Comment by JakubVanek** [comment]
In parallel with https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk11_build_ev3_linux/56/, I'm building a minimal variant on my notebook:
```
Configuration summary:
* Debug level:    release
* HS debug level: product
* JVM variants:   minimal
* JVM features:   minimal: 'compiler1 link-time-opt minimal serialgc' 
* OpenJDK target: OS: linux, CPU architecture: arm, address length: 32
* Version string: 11.0.1+13-ev3 (11.0.1)
```

**Comment by jabrena** [comment]
It is very nice option. 
We could compare many aspects:

- Build size
- Execution Startup
- Capacity to set jvm flags (JMX, Profiling, RMI, etc..)

**Comment by JakubVanek** [comment]
Here we go:
Minimal build: https://drive.google.com/open?id=1ga7uFeZyWsiWAOrGV0pqLZBo9SBymlEB
Full build: https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk11_build_ev3_linux/lastSuccessfulBuild/artifact/build/jri-ev3.tar.gz

**Comment by JakubVanek** [comment]
Also, an additional factor could be runtime memory usage and performance.

**Comment by jabrena** [comment]
Added for the future analysis:

- Build size
- Execution Startup
- Capacity to set jvm flags (JMX, Profiling, RMI, etc..)
- runtime memory usage 
- performance

**Comment by JakubVanek** [comment]
Full build features for comparison with the minimal:
```
Configuration summary:
* Debug level:    release
* HS debug level: product
* JVM variants:   client
* JVM features:   client: 'cds cmsgc compiler1 epsilongc g1gc jfr jni-check jvmti management nmt parallelgc serialgc services vm-structs' 
* OpenJDK target: OS: linux, CPU architecture: arm, address length: 32
* Version string: 11.0.1+13-ev3 (11.0.1)
```
If we don't settle for the Minimal VM, we might want to remove some of the features (like multiple garbage collectors).

EDIT: Hmmm, as I'm looking at it, maybe the minimal VM doesn't support CDS. Maybe it could be added to the configuration.

**Comment by JakubVanek** [comment]
Hmmm, the linked builds may not be comparable. I have noticed that one is compressed and the other is not. When it is needed, I will rebuild both versions.

**Comment by jabrena** [comment]
Hehehe, you store your thoughts in the issues like a diary. :)

**Comment by JakubVanek** [comment]
I have just remembered that Jenkins deletes builds after some time, so I was backing up the Client VM build and I noticed the problem while doing that.

**Comment by JakubVanek** [comment]
Feature comparison for the minimal variant:
```
client default: cds cmsgc compiler1 dtrace epsilongc g1gc jfr jni-check jvmti management nmt parallelgc serialgc services vm-structs`
new default:    cds       compiler1                       jfr           jvmti management nmt            serialgc services vm-structs link-time-opt minimal
```

**Comment by JakubVanek** [comment]
There were some problems with minimal on the newer JDKs - I think the build then failed to link. Closing.
