### ISSUE TITLE
Permission denied when running ./prepare.sh

### ISSUE THREAD

**Issue by scprotz** [ev3dev-lang-java/openjdk-ev3#33]
I was trying to build JDK 10 and following the instructions, but ended up getting the following error:

dpkg-architecture: warning: specified GNU system type arm-linux-gnueabi does not match CC system type x86_64-linux-gnu, try setting a correct CC environment variable
[PREPARE] Downloading host JDK
/build/openjdk-10.0.2_linux-x64_bin.tar.gz: Permission denied

Any suggestions on how to get past it?

I'm on MacOs Mojave using Docker Desktop 2.0.0.3

**Comment by JakubVanek** [comment]
Hi @scprotz,

are you mounting the /build volume? If yes (I'd recommend it), it may be that the user inside Docker has to have write access to it too. It is ugly, but something along "`chmod -R 777 /path/on/host`" should do it.

Regards,

Jakub

**Comment by JakubVanek** [comment]
Superseded by #34. Closing.
