### ISSUE TITLE
Following build instructions on home page fails at #3 because no file system/stretch/Dockerfile.armel exists

### ISSUE THREAD

**Issue by scprotz** [ev3dev-lang-java/openjdk-ev3#34]
I followed the instructions on the landing page.  On step 3, from the cloned git directory, I ran the code, but no file 'system/stretch/Dockerfile.armel' exists.  

`>sudo docker build -t ev3dev-lang-java:jdk-stretch -f system/stretch/Dockerfile.armel system
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/user/git/openjdk-ev3/system/stretch: no such file or directory
`
I swapped it for system/Dockerfile.cross (assuming this is cross-platform from x86->ARMv5).

This kinda works, but then gets stuck at the next step because it says pull accessd denied for ev3dev-lang-java, repository does not exist.

`sudo docker build -t ev3dev-lang-java:jdk-build  --build-arg DEBIAN_RELEASE=stretch  -f scripts/Dockerfile scripts
Sending build context to Docker daemon  202.8kB
Step 1/16 : ARG DEBIAN_RELEASE=stretch
Step 2/16 : ARG BUILD_TYPE=cross
Step 3/16 : FROM ev3dev-lang-java:jdk-$BUILD_TYPE-$DEBIAN_RELEASE
pull access denied for ev3dev-lang-java, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
`

Any help with the instructions?

I'm on Ubuntu 18.04.2.

**Comment by JakubVanek** [comment]
Hi @scprotz,

yup, the README wasn't updated after migrating to ARM-native builds. However, x86->ARM builds should still work. The best source for this is probably `Jenkinsfile`, as that is used for build.

The following script should work, but I haven't tested it.
```bash
# define parameters
TARGET_WORKSPACE="$(pwd)/build" # 10 GB of free space should be sufficient, probably less
TARGET_DEBIAN_VERSION="stretch" # stretch or buster
TARGET_OPENJDK_VERSION="11" # 11 most likely working
                            # 9, 10 may work
                            # 12 is currently broken because a backported patch is now applied in upstream 12 as well
                            # 13 is currently broken because of a conflict in another patch

# prepare working directory
mkdir -p "$TARGET_WORKSPACE"
chmod -R 777 "$TARGET_WORKSPACE" # docker may not share UID with the current user

# build base system container
docker build --build-arg DEBIAN_RELEASE="$TARGET_DEBIAN_VERSION" \
             --build-arg ARCH="armel" \
             --tag "ev3dev-lang-java:jdk-cross-$TARGET_DEBIAN_VERSION" \
             --file ./system/Dockerfile.cross \
             ./system

# on top of that, create a build scripts container
docker build --build-arg commit="$(git rev-parse HEAD)" \
             --build-arg extra="Manual build #1 by $(whoami)" \
             --build-arg DEBIAN_RELEASE="$TARGET_DEBIAN_VERSION" \
             --build-arg BUILD_TYPE="cross" \
             --tag "ev3dev-lang-java:jdk-cross-build" \
             ./scripts

# now run the build
docker run --rm \
           --interactive \
           --tty \
           --volume "$TARGET_WORKSPACE:/build" \
           --env JDKVER="$TARGET_OPENJDK_VERSION" \
           --env JDKVM="client" \
           --env JDKPLATFORM="ev3" \
           --env AUTOBUILD="1" \
           ev3dev-lang-java:jdk-cross-build

# finally, make workspace accessible for all users (i.e. current one too) and list files in its root
chmod -R 777 "$TARGET_WORKSPACE"
# and list the output directory (now it should contain three *-ev3.tar.gz files)
ls "$TARGET_WORKSPACE"
```

Regards,

Jakub

**Comment by JakubVanek** [comment]
I have removed some unnecessary patches and rebased the rest, so JDK 12 should work too. JDK13 is actually building on jenkins as `tip` for `TARGET_OPENJDK_VERSION`. It should work too now.

**Comment by JakubVanek** [comment]
Yup, builds for the following `TARGET_JDK_VERSION` and `TARGET_DEBIAN_VERSION` combinations passed (although in ARMv8/7->ARMv5 way):
* `11` for `stretch`: [openjdk11_build_ev3_linux_native#11](https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk11_build_ev3_linux_native/11/)
* `11` for `buster`: [openjdk11_build_ev3_linux_native_next#11](https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk11_build_ev3_linux_native_next/11/)
* `12` for `buster`: [openjdk12_build_ev3_linux_native#13](https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk12_build_ev3_linux_native/13/)
* `tip` for `buster`: [openjdk13_build_ev3_linux_native#25](https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk13_build_ev3_linux_native/25/)

**Comment by scprotz** [comment]
I tested with the build script provided.  It built the JVM.  After moving it over to an ev3 running stretch, the JVM, just to check the version, takes over 8 seconds.  As great as it is to have Java running on ev3, this wouldn't be anywhere near fast enough for competition.  Is there a way to get the JVM to start even quicker? (or make it even lighter)?

`robot@ev3dev:~/java/ev3jvm/jdk/bin$ time ./java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-ev3)
OpenJDK Client VM (build 11.0.4+11-ev3, mixed mode)

real	0m8.364s
user	0m6.453s
sys	0m0.451s
`

**Comment by JakubVanek** [comment]
Hi,

thanks for the reply!

I have a few ideas:
* Try using the `jri-ev3.tar.gz` archive, which contains only a subset of Java packages/modules.
* It is also possible to regenerate the JRI archive with module compression enabled. This could achieve some speedup if the I/O throughput is slowing it down. On the other hand, decompression could slow it down. To try it out:
   1. run shell within the build container:
      ```sh
      docker run --rm \
                 --interactive \
                 --tty \
                 --volume "$TARGET_WORKSPACE:/build" \
                 --env JDKVER="$TARGET_OPENJDK_VERSION" \
                 --env JDKVM="client" \
                 --env JDKPLATFORM="ev3" \
                 --env AUTOBUILD="1" \
                 ev3dev-lang-java:jdk-cross-build \
                 /bin/bash
      ```
   2. Open the `/opt/jdkcross/zip.sh` file in that shell with `sudo nano` or other editor. On lines 27-34 is the jlink command, which generates the reduced image. Looking into the jlink manpage, `--compress 2` option could make a difference. `--strip-debug` could be useful too.
   3. Run the zip script; the output archives will be generated in the workspace directory:
      ```sh
      /bin/bash /opt/jdkcross/zip.sh
      ```
   4. Exit the container.
* Strip debugging symbols from all JVM binaries and libraries (default output contains all debug info for debian repackaging). This can be done also from outside of the build container:
   ```sh
   # requires to have findutils and binutils-arm-linux-gnueabi (on x86) or binutils (on arm) packages installed
   find <extracted jvm root directory> -type f -exec arm-linux-gnueabi-strip --strip-unneeded {} \;
   ```
* After uploading the JVM, generate the CDS archive on-brick:
   ```sh
   <jvm root directory>/bin/java -Xshare:dump
   ```
* Try running JVM with `-noverify` or `-XX:TieredStopAtLevel=1` switches.
* Try overclocking the EV3 to 375 or 456 MHz by editing `/boot/flash/uEnv.txt` and rebooting.

Regards,

Jakub

**Comment by scprotz** [comment]
I tested  jri.  It was about 1 second faster (now down to 7 seconds to just
do ./java --version).

It does seem I/O bound (this is also one of the problems for python too I
think.  I tried your suggestion on compressing and removing debug.  I could
do steps 1 and 2.  On step 3 I get this:

compiler@c72bf39c94c0:/opt/jdkcross$ /bin/bash /opt/jdkcross/zip.sh
> dpkg-architecture: warning: specified GNU system type arm-linux-gnueabi
> does not match CC system type x86_64-linux-gnu, try setting a correct CC
> environment variable
> /opt/jdkcross/zip.sh: line 8: cd:
> /build/jdk/build/linux-arm-normal-client-release/images: No such file or
> directory


Any suggestions on what I'm missing?

**Comment by JakubVanek** [comment]
I think it might be due to the workspace directory - it needs to be mounted where it was before. Alternatively, if you have JDK11 installed (Ubuntu 18.04 luckily has it as its default version), it should be possible to create JRI directly by invoking the x86-native jlink on the host computer:
```sh
# extract jmods, from which the JRI (or even full JDK) can be assembled
tar -xf <path to jlink.tar.gz>
# create the JRI
jlink \
   --module-path ./jmods/ \
   --endian little \
   --compress 2 \
   --strip-debug \
   --no-header-files \
   --no-man-pages \
   --add-modules "$JRI_MODULES" \
   --output ./jri
# also strip debug symbols
find ./jri -type f -exec arm-linux-gnueabi-strip --strip-unneeded {} \;
```

**Comment by JakubVanek** [comment]
Edit: I have forgotten to replace the JRI_MODULES variable with its contents. It should be fixed now.

**Comment by scprotz** [comment]
I ran this on my Ubuntu 18.04 (x86-64) desktop.  got a bunch of messages like:

 arm-linux-gnueabi-strip: ./jri/lib/libfontmanager.so: File format not recognized.  

Did I do something wrong there?

**Comment by JakubVanek** [comment]
This is strange... There should be messages like this, but only for non-executable files:
```sh
kuba@ntb:~$ rm -rf jri jmods
kuba@ntb:~$ tar -xf jmods-ev3.tar.gz # taken from https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk11_build_ev3_linux_native/lastSuccessfulBuild/artifact/build/jmods-ev3.tar.gz
                                     # hmmm, it's jmods-ev3.tar.gz, not jlink.tar.gz (typo in my previous reply)
kuba@ntb:~$ jlink \
>    --module-path ./jmods/ \
>    --endian little \
>    --compress 2 \
>    --strip-debug \
>    --no-header-files \
>    --no-man-pages \
>    --add-modules "java.se,jdk.jdwp.agent,jdk.unsupported,jdk.management.agent,jdk.jartool" \
>    --output ./jri
kuba@ntb:~$ find ./jri -type f -exec arm-linux-gnueabi-strip --strip-unneeded {} \;
arm-linux-gnueabi-strip:./jri/lib/modules: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/tzdb.dat: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/jrt-fs.jar: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/security/cacerts: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/security/default.policy: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/security/blacklisted.certs: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/security/public_suffix_list.dat: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/jvm.cfg: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/client/Xusage.txt: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/classlist: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/psfont.properties.ja: File format not recognized
arm-linux-gnueabi-strip:./jri/lib/psfontj2d.properties: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/management/management.properties: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/management/jmxremote.access: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/management/jmxremote.password.template: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/security/java.policy: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/security/policy/unlimited/default_US_export.policy: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/security/policy/unlimited/default_local.policy: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/security/policy/README.txt: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/security/policy/limited/exempt_local.policy: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/security/policy/limited/default_US_export.policy: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/security/policy/limited/default_local.policy: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/security/java.security: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/net.properties: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/sound.properties: File format not recognized
arm-linux-gnueabi-strip:./jri/conf/logging.properties: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.desktop/opengl.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.desktop/harfbuzz.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.desktop/mesa3d.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.desktop/colorimaging.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.desktop/xwindows.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/c-libutl.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/cldr.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/asm.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/ASSEMBLY_EXCEPTION: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/ADDITIONAL_LICENSE_INFO: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/public_suffix.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/aes.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/LICENSE: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/unicode.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.base/icu.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.xml.crypto/santuario.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.xml/xalan.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.xml/bcel.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.xml/dom.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.xml/jcup.md: File format not recognized
arm-linux-gnueabi-strip:./jri/legal/java.xml/xerces.md: File format not recognized
arm-linux-gnueabi-strip:./jri/release: File format not recognized
kuba@ntb:~$ 
```

**Comment by JakubVanek** [comment]
What does the following command output?
```sh
file ./jri/lib/libfontmanager.so
```
After the commands above, for me it prints this: 
```sh
kuba@ntb:~$ file ./jri/lib/libfontmanager.so
./jri/lib/libfontmanager.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=5aedd097603ef47e0eebe0cf553203e6004dbd5e, stripped
```

**Comment by scprotz** [comment]
I re-followed the instructions and looks like I came out with same results as you displayed this time.  

So with the small JVM and stripped files my results didn't change much after building the JRI:

time ./java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-ev3)
OpenJDK Client VM (build 11.0.4+11-ev3, mixed mode)

real	0m7.274s
user	0m5.446s
sys	0m0.403s


As much as I love to use Java, it just doesn't look like it'll be very competitive in Lego Mindstorms competitions, as a 7+ second startup time isn't very usable.

I'd definitely love to hear any other ideas on making Java a competitive language.

**Comment by JakubVanek** [comment]
Hi,

have you tried dumping the CDS cache and overclocking the brick? However it is possible that the 7 seconds are really the lower bound of the startup time. I would like to think that I have seen a 3-second startup, but I'm not really sure it is real.

If you need fast startup and fast runtime, then, at least on embedded, native compled langauges will probably beat everything. I have had experience with these projects:
* EV3RT - http://ev3rt-git.github.io/
  * It's cool
    * It's a real RTOS
    * It's C, but C++ should work too
    * It really boots up from powered-off brick to a running program in ~6 seconds.
    * It's not hard to modify the system, including the sensor/motor drivers.
  * However it's also hard to debug if something bad breaks
    * To be safe, it's good to have an "[ev3 console cable](https://www.google.com/search?q=ev3+console+cable)". It allows getting some info from even more severe crashes.
    * The problem with debugging is that (AFAIK) GDB server over the console doesn't exist yet there, so step debugging is not an option. 
    * In case of a bad crash, you can sometimes discover something from the output, sometimes not.
  * It's not very widely known (AFAIK), so there might not be many libraries for it (but it depends)
  * It doesn't use an Unix-like API for threading - instead it uses [µITRON 4.0](https://www.tron.org/wp-content/themes/dp-magjam/pdf/specifications/en_US/TEF024-S001-04.03.00_en.pdf)
  * I don't think the USB host port is usable, however for competitions it should be OK. The slave port is working and it works effectively as a SD card reader.
  * I got some strange crashes that make the brick go off. However this may likely be due to some of my changes.
* ev3dev with C++ - via [ev3dev-lang-cpp](https://github.com/ddemidov/ev3dev-lang-cpp) or other library
  * You still have to boot Linux, but after that it's fast too
  * It's quite easy to debug
    * There is a full Linux running, so you can either:
      * have a gdbserver running on the brick and connect to it via GDB (or via IDE)
      * run full GDB on the brick
    * The kernel is stable, so it will hardly ever crash the entire brick
  * It's easier to code for it than it's for EV3RT.
  * For GUI, you can use something like ncurses or newt
  * You can upload programs via SSH and network (on EV3RT it's harder)
  * It still allows you to use many libraries, and many of them could be already in Debian
  * It's not a hard RTOS, but this may not be a problem. However you can still use the realtime scheduling priority via SCHED_FIFO.

Regards,

Jakub

**Comment by scprotz** [comment]
I've also tried a number of options to date for Lego Mindstorms:

Python has a slow startup like Java (about 7 seconds)
EV3 block programming is fast, but not a very good place to teach good
coding practices (the OS is also very clunky and glitchy, especially with
wireless and bluetooth)
Perl is fast, but not an ideal language for middle schoolers (and a bit
niche)
Bash is not a programming language really at all, but is quite fast to
interact with the ev3.

I've recently looked at using JSDB, as a Javascript engine and have been
able to get it to run and it appears that it will be able to interact very
quickly with the EV3DEV environment.  There is currently no EV3 libraries
designed for generic javascript (only the node.js/typescript ones).  I may
see about porting them over.

I'm also trying some other VMs that might have reasonable Java support and
run on the ev3 (like JAMVM).

I'd like to find a fast, minimal, JVM for now that can support it, and like
linux, I feel like the current JDKs are just too big and bloated to really
run on these small systems and have fast startup times. (plus the ARMv5 is
very old)

**Comment by jabrena** [comment]
Hi @scprotz, 

exist one pending alternative. From LEJOS exist a way to load a jar from another Java program loading. In this way, the whole runtime is running and the performance could be increased but this is something that we don't have stable.

Juan Antonio

**Comment by JakubVanek** [comment]
I have updated the readme with the shell script, closing.
