### ISSUE TITLE
Testing Release 0.3.0 on EV3

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/openjdk-ev3#5]

**Comment by jabrena** [comment]
```
wget https://github.com/ev3dev-lang-java/openjdk-9-ev3/releases/download/v0.3/jdk-ev3.zip
wget https://github.com/ev3dev-lang-java/openjdk-9-ev3/releases/download/v0.3/jre-ev3.zip
```

**Comment by jabrena** [comment]
https://askubuntu.com/questions/86849/how-to-unzip-a-zip-file-from-the-terminal

unzip jdk-ev3.zip -d jdk-ev3

update-alternatives --config java

**Comment by jabrena** [comment]
https://introcs.cs.princeton.edu/java/11hello/HelloWorld.java.html

**Comment by jabrena** [comment]
```
robot@brick1:~/jre-ev3/bin$ ./java -version  
openjdk version "9.0.1"
OpenJDK Runtime Environment (build 9.0.1+11)
OpenJDK Client VM (build 9.0.1+11, mixed mode)
```

**Comment by jabrena** [comment]
```
robot@brick1:~/jdk-ev3/jdk-ev3/bin$ ls
jarsigner  javadoc  jcmd      jdeprscan  jimage  jlink  jps         jstack  keytool  rmic         schemagen   tnameserv  wsimport
idlj              java       javah    jconsole  jdeps      jinfo   jmap   jrunscript  jstat   orbd     rmid         serialver   unpack200  xjc
jar               javac      javap    jdb       jhsdb      jjs     jmod   jshell      jstatd  pack200  rmiregistry  servertool  wsgen
```

**Comment by JakubVanek** [comment]
If the intent is only to allow running Java programs, please use only `jre-ev3.zip`. And to make the start faster, run `java -Xshare:dump`.

**Comment by jabrena** [comment]
Good morning @JakubVanek yes, I agree with you, for the normal usage scenario, everyone should the JRE deliverable. Today I will test the jvm with that flag. Yesterday I tested a bit a Kotlin example with the new JVM: https://github.com/ev3dev-lang-java/examples/tree/master/helloWorldKotlin
but today I will retest again.

With previous stable JRE, Oracle JRE 8, the time to execute a Hello World was 8 seconds. With latest OpenJDK 9, build 11, the time is around 13 seconds. Today I will test with the jvm flag. I am adding this dev notes in the issue for the documentation process which I will have to do:
http://ev3dev-lang-java.github.io/docs/support/getting_started/brick.html

**Comment by jabrena** [comment]
I have to review the process to add a new JVM in the brick or the scenario to add a new JVM in a brick where previously existed a previous version and what is the command to set the jvm:

https://askubuntu.com/questions/315646/update-java-alternatives-vs-update-alternatives-config-java

sudo update-alternatives --config java

**Comment by jabrena** [comment]
Nice jvm flag:
https://docs.oracle.com/javase/7/docs/technotes/guides/vm/class-data-sharing.html

**Comment by jabrena** [comment]
Amazing results:

```
robot@brick1:~/jre-ev3/bin$ ./java -Xshare:dump
Allocated shared space: 29605888 bytes at 0x80000000
Loading classes to share ...
Loading classes to share: done.
Rewriting and linking classes ...
Rewriting and linking classes: done
Number of classes 1191
    instance classes   =  1177
    obj array classes  =     6
    type array classes =     8
Updating ConstMethods ... done. 
Removing unshareable information ... done. 
ro space:   3863080 [ 33.8% of total] out of   6291456 bytes [ 61.4% used] at 0x80000000
rw space:   2890216 [ 25.3% of total] out of   6291456 bytes [ 45.9% used] at 0x80600000
md space:     48020 [  0.4% of total] out of   2097152 bytes [  2.3% used] at 0x80c00000
mc space:     27744 [  0.2% of total] out of    122880 bytes [ 22.6% used] at 0x80e00000
st space:         0 [  0.0% of total] out of         0 bytes [100.0% used] at 0x00000000
od space:   4610880 [ 40.3% of total] out of  12582912 bytes [ 36.6% used] at 0x80e1e000
total   :  11439940 [100.0% of total] out of  27385856 bytes [ 41.8% used]
robot@brick1:~/jre-ev3/bin$ ./java HelloWorld       
Hello, World
``` 

The same performance than Oracle JRE 8.
Another Script to execute in the session startup.

Juan Antonio

**Comment by jabrena** [comment]
Hi @JakubVanek, if you know more `jvm` flags to increase the performance or some ways to tune the `ev3dev` to boost java processes, I would like to listen your ideas.

Good night.

Juan Antonio

**Comment by JakubVanek** [comment]
>  Another Script to execute in the session startup.

It is only needed to be run after the modules are updated, i.e. after the installation.

> Hi @JakubVanek, if you know more jvm flags to increase the performance or some ways to tune the ev3dev to boost java processes, I would like to listen your ideas.

Yes, I have an idea. _Please,_ consider adding an option to remove the dependency on SLF4J and LogBack from the library. This way, it is possible to make the second class loading phase multiple times faster.

I've tried bypassing the logging libraries by removing them and instead using this simple wrapper:
```java
package org.slf4j;

public class LoggerFactory {
    private static Logger log = new Logger();
    
    public static Logger getLogger(Class<?> wut) {
        return log;
    }
}
```
```java
package org.slf4j;

public class Logger {
    public Logger() {
        
    }
    public void debug(Object... objs) {
        
    }
    public void error(Object... objs) {
        
    }
    public void info(Object... objs) {
        
    }
    public void trace(Object... objs) {
        
    }
    public void warn(Object... objs) {
        
    }
    public boolean isDebugEnabled() {
        return false;
    }
    public boolean isTraceEnabled() {
        return false;
    }

}
```
The change was noticeable immediately.

**Comment by jabrena** [comment]
Hi @JakubVanek,

If you like, create a issue about Logging features on this repo:
https://github.com/ev3dev-lang-java/ev3dev-lang-java

The idea is quite interesting, I would like to listen your feedback from a performance perspective.

Cheers

Juan Antonio

**Comment by jabrena** [comment]
Old release
