### ISSUE TITLE
Notes for next release v0.4.0

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/openjdk-ev3#6]
Hi @JakubVanek,

Currently, the releases represent mayor version and minor version, we should follow Semver specification: x.y.z
https://semver.org/

In relation to the zip version, is it possible to compress using the file format tar.gz. I say it because I am not sure if ev3dev has zip debian package installed by default but the command tar is available out of box.

This week, I will upgrade the installer:
https://github.com/ev3dev-lang-java/installer/blob/master/modules/java.sh

Later, with the installer stable, I will upgrade the template project to automate the installer process in the brick in an autonomous way:
https://github.com/ev3dev-lang-java/template_project_gradle/blob/master/deploy.gradle

Juan Antonio

**Comment by JakubVanek** [comment]
Hi,

> we should follow Semver specification: x.y.z

Yes, I think that is a good idea. I've heard of it before, but I haven't tried using it.

> In relation to the zip version, is it possible to compress using the file format tar.gz. I say it because I am not sure if ev3dev has zip debian package installed by default but the command tar is available out of box.

No, I also think it hasn't the unzip package installed by default. I've skipped the `.tar.*` because I tried only with `.tar.xz` and `xz-utils` package also wasn't installed by default.

Jakub Vaněk

**Comment by jabrena** [comment]
Hi @JakubVanek,

I think that this command run by default in EV3Dev:

`tar -zxvf "/home/robot/ejdk-8-fcs-b132-linux-arm-sflt-03_mar_2014.tar.gz" -C /opt`

But I will test from a clean image this week.

Later, I will continue with the tests.

Juan Antonio

**Comment by JakubVanek** [comment]
Hmmm, I forgot about the gzip compression for v4.0. But it should be easy to add (swapping `zip -r ...` with `tar -czf ...`)

**Comment by jabrena** [comment]
Don´t worry for the next OpenJDK 10 release. :)

I had to install 7z to unzip the release.

**Comment by JakubVanek** [comment]
Switched to .tar.gz format.
I'm trying to follow semver somehow.
