### ISSUE TITLE
Maintainers Wanted

### ISSUE THREAD

**Issue by JakubVanek** [ev3dev-lang-java/openjdk-ev3#69]
This subproject is looking for maintainers and contributors. If you'd like to take part in it, please contact @jabrena over at https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues to get started. If you have any questions related to the current subproject technicalities, you can additionally tag @JakubVanek to get more information.

**Comment by jabrena** [comment]
Sorry @JakubVanek,

This is not way.
