### ISSUE TITLE
Add Travis Support

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/openjdk-ev3#8]

**Comment by JakubVanek** [comment]
https://github.com/ev3dev-lang-java/openjdk-ev3#automatic-build will help with tasks like this.

**Comment by JakubVanek** [comment]
What about https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/466?

**Comment by jabrena** [comment]
We use:
https://ci.adoptopenjdk.net/view/ev3dev/job/openjdk-10-ev3-test/66/console
