### ISSUE TITLE
Rename repository to openjdk-ev3

### ISSUE THREAD

**Issue by jabrena** [ev3dev-lang-java/openjdk-ev3#9]
Hi @JakubVanek,

I am thinking to rename the repo to: openjdk-ev3, because next 20/3/2018, OpenJDK will release Java 10, so, this repo should be more generic in order to maintain all future versions of Java.
http://openjdk.java.net/jeps/322

What do you think?

Juan Antonio

**Comment by jabrena** [comment]
In one branch, we could maintain the project to build `open-jdk9` and in others the same for `open-jdk10` and future versions.

**Comment by JakubVanek** [comment]
Hi,

yeah, I'm OK with that. I've created branches for openjdk-9 and openjdk-10.

What do you think about the master branch? I think we don't need it anymore. One of the JDK version specific ones should be the _default_ branch.

Jakub

**Comment by jabrena** [comment]
Hi mate,

Master is required. All repositories follow Git Flow.
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

This project should integrate in develop the feature branch about OpenJDK 10, in the moment that officially they released but meanwhile, we could release a Snapshot version.
http://openjdk.java.net/jeps/322

This week, I will try to build OpenJDK 10.

Cheers @JakubVanek, you did a good achievement with this repo. :)

**Comment by jabrena** [comment]
Renamed project.
